name: Library generator
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Manual trigger"
  schedule:
    - cron:  '0 6 * * *'

jobs:
  micro_ros_arduino_generate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: foxy
            branch: foxy
          - distro: rolling
            branch: main
          - distro: galactic
            branch: galactic
          - distro: humble
            branch: humble
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y %H:%M')"
      - name: Update libraries
        run: |
          docker run --rm -v $(pwd):/project --env MICROROS_LIBRARY_FOLDER=extras microros/micro_ros_static_library_builder:${{ matrix.distro }}
          sudo chown -R $(whoami) .
          sudo chmod -R 777 .
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: micro-ROS ${{ matrix.distro }} Library auto-update ${{ steps.date.outputs.date }}
          title: micro-ROS Library auto-update ${{ steps.date.outputs.date }}
          body: This PR is autogenerated and updates the micro-ROS Arduino library. Close and reopen to trigger CI.
          branch: autoupdate_micro_ros_arduino_${{ matrix.branch }}
          delete-branch: true
          reviewers: pablogs9
          base: ${{ matrix.branch }}

